// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Square$ReactTemplate = require("./Square.bs.js");

var boardRow_000 = Css.borderBottom(Css.px(5), Css.solid, Css.hex("DDDDDD"));

var boardRow_001 = /* :: */[
  Css.display(Css.flexBox),
  /* :: */[
    Css.justifyContent(Css.center),
    /* [] */0
  ]
];

var boardRow = /* :: */[
  boardRow_000,
  boardRow_001
];

var lastBoardRow_000 = Css.borderWidth(Css.px(0));

var lastBoardRow = /* :: */[
  lastBoardRow_000,
  /* [] */0
];

var component = ReasonReact.statelessComponent("BoardRow");

function make(gameState, row, onMark, index, isLastRow, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var className = $$String.concat(" ", /* :: */[
                    Css.style(boardRow),
                    /* :: */[
                      isLastRow ? Css.style(lastBoardRow) : "",
                      /* [] */0
                    ]
                  ]);
              return React.createElement("div", {
                          className: className
                        }, $$Array.of_list(List.mapi((function (ind, value) {
                                    var id = String(index) + String(ind);
                                    return ReasonReact.element(id, undefined, Square$ReactTemplate.make(value, gameState, (function (param) {
                                                      return Curry._1(onMark, id);
                                                    }), List.length(row) === (ind + 1 | 0), /* array */[]));
                                  }), row)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.boardRow = boardRow;
exports.lastBoardRow = lastBoardRow;
exports.component = component;
exports.make = make;
/* boardRow Not a pure module */
