// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./Utils.bs.js");

Css.insertRule(Utils$ReactTemplate.cssButtonReset);

var buttonSquare_000 = Css.flexBasis(Css.em(33.3));

var buttonSquare_001 = /* :: */[
  Css.padding(Css.em(3.0)),
  /* [] */0
];

var buttonSquare = /* :: */[
  buttonSquare_000,
  buttonSquare_001
];

var component = ReasonReact.statelessComponent("Square");

function make(value, gameState, onMark, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("button", {
                          className: Css.style(buttonSquare)
                        }, Utils$ReactTemplate.toString("Hi"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.buttonSquare = buttonSquare;
exports.component = component;
exports.make = make;
/*  Not a pure module */
