// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var game = Css.style(/* :: */[
      Css.background(Css.red),
      /* [] */0
    ]);

exports.game = game;
/* game Not a pure module */
